/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ClientErrorResponse } from '../models';
// @ts-ignore
import { Partner } from '../models';
// @ts-ignore
import { PartnerList } from '../models';
// @ts-ignore
import { ServerErrorResponse } from '../models';
// @ts-ignore
import { SubscriptionErrorResponse } from '../models';
// @ts-ignore
import { TooManyRequestsResponse } from '../models';
// @ts-ignore
import { ValidationErrorResponse } from '../models';
/**
 * PartnerApi - axios parameter creator
 * @export
 */
export const PartnerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new partner. Returns a partner object if the create is succeded.
         * @summary Create a partner
         * @param {Partner} partner Partner object that you would like to store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPartner: async (partner: Partner, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'partner' is not null or undefined
            assertParamExists('createPartner', 'partner', partner)
            const localVarPath = `/partners`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-KEY", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(partner, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete an existing partner.
         * @summary Delete a partner
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePartner: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deletePartner', 'id', id)
            const localVarPath = `/partners/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-KEY", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves the details of an existing partner.
         * @summary Retrieve a partner
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPartner: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPartner', 'id', id)
            const localVarPath = `/partners/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-KEY", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of your partners. The partners are returned sorted by creation date, with the most recent partners appearing first.
         * @summary List all partners
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {string} [query] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPartner: async (page?: number, perPage?: number, query?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/partners`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-KEY", configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update an existing partner. Returns a partner object if the update is succeded.
         * @summary Update a partner
         * @param {number} id 
         * @param {Partner} partner Partner object that you would like to update.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePartner: async (id: number, partner: Partner, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updatePartner', 'id', id)
            // verify required parameter 'partner' is not null or undefined
            assertParamExists('updatePartner', 'partner', partner)
            const localVarPath = `/partners/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication api_key required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-KEY", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(partner, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PartnerApi - functional programming interface
 * @export
 */
export const PartnerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PartnerApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a new partner. Returns a partner object if the create is succeded.
         * @summary Create a partner
         * @param {Partner} partner Partner object that you would like to store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPartner(partner: Partner, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Partner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPartner(partner, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Delete an existing partner.
         * @summary Delete a partner
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deletePartner(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deletePartner(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieves the details of an existing partner.
         * @summary Retrieve a partner
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPartner(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Partner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPartner(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a list of your partners. The partners are returned sorted by creation date, with the most recent partners appearing first.
         * @summary List all partners
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {string} [query] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPartner(page?: number, perPage?: number, query?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PartnerList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPartner(page, perPage, query, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Update an existing partner. Returns a partner object if the update is succeded.
         * @summary Update a partner
         * @param {number} id 
         * @param {Partner} partner Partner object that you would like to update.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePartner(id: number, partner: Partner, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Partner>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePartner(id, partner, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PartnerApi - factory interface
 * @export
 */
export const PartnerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PartnerApiFp(configuration)
    return {
        /**
         * Create a new partner. Returns a partner object if the create is succeded.
         * @summary Create a partner
         * @param {Partner} partner Partner object that you would like to store.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPartner(partner: Partner, options?: any): AxiosPromise<Partner> {
            return localVarFp.createPartner(partner, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete an existing partner.
         * @summary Delete a partner
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deletePartner(id: number, options?: any): AxiosPromise<void> {
            return localVarFp.deletePartner(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves the details of an existing partner.
         * @summary Retrieve a partner
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPartner(id: number, options?: any): AxiosPromise<Partner> {
            return localVarFp.getPartner(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of your partners. The partners are returned sorted by creation date, with the most recent partners appearing first.
         * @summary List all partners
         * @param {number} [page] 
         * @param {number} [perPage] 
         * @param {string} [query] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPartner(page?: number, perPage?: number, query?: string, options?: any): AxiosPromise<PartnerList> {
            return localVarFp.listPartner(page, perPage, query, options).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing partner. Returns a partner object if the update is succeded.
         * @summary Update a partner
         * @param {number} id 
         * @param {Partner} partner Partner object that you would like to update.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePartner(id: number, partner: Partner, options?: any): AxiosPromise<Partner> {
            return localVarFp.updatePartner(id, partner, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PartnerApi - interface
 * @export
 * @interface PartnerApi
 */
export interface PartnerApiInterface {
    /**
     * Create a new partner. Returns a partner object if the create is succeded.
     * @summary Create a partner
     * @param {Partner} partner Partner object that you would like to store.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerApiInterface
     */
    createPartner(partner: Partner, options?: AxiosRequestConfig): AxiosPromise<Partner>;

    /**
     * Delete an existing partner.
     * @summary Delete a partner
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerApiInterface
     */
    deletePartner(id: number, options?: AxiosRequestConfig): AxiosPromise<void>;

    /**
     * Retrieves the details of an existing partner.
     * @summary Retrieve a partner
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerApiInterface
     */
    getPartner(id: number, options?: AxiosRequestConfig): AxiosPromise<Partner>;

    /**
     * Returns a list of your partners. The partners are returned sorted by creation date, with the most recent partners appearing first.
     * @summary List all partners
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {string} [query] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerApiInterface
     */
    listPartner(page?: number, perPage?: number, query?: string, options?: AxiosRequestConfig): AxiosPromise<PartnerList>;

    /**
     * Update an existing partner. Returns a partner object if the update is succeded.
     * @summary Update a partner
     * @param {number} id 
     * @param {Partner} partner Partner object that you would like to update.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerApiInterface
     */
    updatePartner(id: number, partner: Partner, options?: AxiosRequestConfig): AxiosPromise<Partner>;

}

/**
 * PartnerApi - object-oriented interface
 * @export
 * @class PartnerApi
 * @extends {BaseAPI}
 */
export class PartnerApi extends BaseAPI implements PartnerApiInterface {
    /**
     * Create a new partner. Returns a partner object if the create is succeded.
     * @summary Create a partner
     * @param {Partner} partner Partner object that you would like to store.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerApi
     */
    public createPartner(partner: Partner, options?: AxiosRequestConfig) {
        return PartnerApiFp(this.configuration).createPartner(partner, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete an existing partner.
     * @summary Delete a partner
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerApi
     */
    public deletePartner(id: number, options?: AxiosRequestConfig) {
        return PartnerApiFp(this.configuration).deletePartner(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves the details of an existing partner.
     * @summary Retrieve a partner
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerApi
     */
    public getPartner(id: number, options?: AxiosRequestConfig) {
        return PartnerApiFp(this.configuration).getPartner(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of your partners. The partners are returned sorted by creation date, with the most recent partners appearing first.
     * @summary List all partners
     * @param {number} [page] 
     * @param {number} [perPage] 
     * @param {string} [query] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerApi
     */
    public listPartner(page?: number, perPage?: number, query?: string, options?: AxiosRequestConfig) {
        return PartnerApiFp(this.configuration).listPartner(page, perPage, query, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an existing partner. Returns a partner object if the update is succeded.
     * @summary Update a partner
     * @param {number} id 
     * @param {Partner} partner Partner object that you would like to update.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PartnerApi
     */
    public updatePartner(id: number, partner: Partner, options?: AxiosRequestConfig) {
        return PartnerApiFp(this.configuration).updatePartner(id, partner, options).then((request) => request(this.axios, this.basePath));
    }
}

