/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Currency = {
    Aed: 'AED',
    Aud: 'AUD',
    Bgn: 'BGN',
    Brl: 'BRL',
    Cad: 'CAD',
    Chf: 'CHF',
    Cny: 'CNY',
    Czk: 'CZK',
    Dkk: 'DKK',
    Eur: 'EUR',
    Gbp: 'GBP',
    Hkd: 'HKD',
    Hrk: 'HRK',
    Huf: 'HUF',
    Idr: 'IDR',
    Ils: 'ILS',
    Inr: 'INR',
    Isk: 'ISK',
    Jpy: 'JPY',
    Krw: 'KRW',
    Mxn: 'MXN',
    Myr: 'MYR',
    Nok: 'NOK',
    Nzd: 'NZD',
    Php: 'PHP',
    Pln: 'PLN',
    Ron: 'RON',
    Rsd: 'RSD',
    Rub: 'RUB',
    Sek: 'SEK',
    Sgd: 'SGD',
    Thb: 'THB',
    Try: 'TRY',
    Uah: 'UAH',
    Usd: 'USD',
    Zar: 'ZAR'
} as const;

export type Currency = typeof Currency[keyof typeof Currency];



