/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBlock } from './document-block';

/**
 * A object with a data property that contains an array of up to limit document blocks. Each entry in the array is a separate document block object. If no more document block are available, the resulting array will be empty.
 * @export
 * @interface DocumentBlockList
 */
export interface DocumentBlockList {
    /**
     * 
     * @type {Array<DocumentBlock>}
     * @memberof DocumentBlockList
     */
    'data'?: Array<DocumentBlock>;
    /**
     * 
     * @type {number}
     * @memberof DocumentBlockList
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentBlockList
     */
    'per_page'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentBlockList
     */
    'current_page'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentBlockList
     */
    'last_page'?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentBlockList
     */
    'prev_page_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentBlockList
     */
    'next_page_url'?: string;
}

