/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Entitlement } from './entitlement';
// May contain unused imports in some cases
// @ts-ignore
import { Vat } from './vat';

/**
 * 
 * @export
 * @interface DocumentItem
 */
export interface DocumentItem {
    /**
     * 
     * @type {number}
     * @memberof DocumentItem
     */
    'product_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentItem
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentItem
     */
    'net_unit_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentItem
     */
    'quantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentItem
     */
    'unit'?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentItem
     */
    'net_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentItem
     */
    'gross_amount'?: number;
    /**
     * 
     * @type {Vat}
     * @memberof DocumentItem
     */
    'vat'?: Vat;
    /**
     * 
     * @type {number}
     * @memberof DocumentItem
     */
    'vat_amount'?: number;
    /**
     * 
     * @type {Entitlement}
     * @memberof DocumentItem
     */
    'entitlement'?: Entitlement;
    /**
     * 
     * @type {string}
     * @memberof DocumentItem
     */
    'comment'?: string;
}



