/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentBlockType } from './document-block-type';

/**
 * 
 * @export
 * @interface DocumentBlock
 */
export interface DocumentBlock {
    /**
     * 
     * @type {number}
     * @memberof DocumentBlock
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentBlock
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentBlock
     */
    'prefix'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentBlock
     */
    'custom_field1'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentBlock
     */
    'custom_field2'?: string;
    /**
     * 
     * @type {DocumentBlockType}
     * @memberof DocumentBlock
     */
    'type'?: DocumentBlockType;
}



