/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentVatRateSummary } from './document-vat-rate-summary';

/**
 * 
 * @export
 * @interface DocumentSummary
 */
export interface DocumentSummary {
    /**
     * 
     * @type {number}
     * @memberof DocumentSummary
     */
    'net_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentSummary
     */
    'net_amount_local'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentSummary
     */
    'gross_amount_local'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentSummary
     */
    'vat_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentSummary
     */
    'vat_amount_local'?: number;
    /**
     * 
     * @type {Array<DocumentVatRateSummary>}
     * @memberof DocumentSummary
     */
    'vat_rate_summary'?: Array<DocumentVatRateSummary>;
}

