/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Address } from './address';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentBankAccount } from './document-bank-account';

/**
 * 
 * @export
 * @interface DocumentOrganization
 */
export interface DocumentOrganization {
    /**
     * 
     * @type {string}
     * @memberof DocumentOrganization
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentOrganization
     */
    'tax_number'?: string;
    /**
     * 
     * @type {DocumentBankAccount}
     * @memberof DocumentOrganization
     */
    'bank_account'?: DocumentBankAccount;
    /**
     * 
     * @type {Address}
     * @memberof DocumentOrganization
     */
    'address'?: Address;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentOrganization
     */
    'small_taxpayer'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DocumentOrganization
     */
    'ev_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentOrganization
     */
    'eu_tax_number'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentOrganization
     */
    'cash_settled'?: boolean;
}

