/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CorrectionType } from './correction-type';
// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import { Discount } from './discount';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentAncestor } from './document-ancestor';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentItem } from './document-item';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentLanguage } from './document-language';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentNotificationStatus } from './document-notification-status';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentOrganization } from './document-organization';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentPartner } from './document-partner';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentSettings } from './document-settings';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentSummary } from './document-summary';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentType } from './document-type';
// May contain unused imports in some cases
// @ts-ignore
import { OnlineSzamlaStatusEnum } from './online-szamla-status-enum';
// May contain unused imports in some cases
// @ts-ignore
import { Partner } from './partner';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentMethod } from './payment-method';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentStatus } from './payment-status';

/**
 * Document object representing your invoice. NOTE: partner property is deprecated. Please use document_partner instead.
 * @export
 * @interface Document
 */
export interface Document {
    /**
     * The document\'s unique identifier.
     * @type {number}
     * @memberof Document
     */
    'id'?: number;
    /**
     * The document\'s invoice number.
     * @type {string}
     * @memberof Document
     */
    'invoice_number'?: string;
    /**
     * 
     * @type {DocumentType}
     * @memberof Document
     */
    'type'?: DocumentType;
    /**
     * 
     * @type {boolean}
     * @memberof Document
     */
    'cancelled'?: boolean;
    /**
     * DocumentBlock\'s identifier.
     * @type {number}
     * @memberof Document
     */
    'block_id'?: number;
    /**
     * 
     * @type {PaymentStatus}
     * @memberof Document
     */
    'payment_status'?: PaymentStatus;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof Document
     */
    'payment_method'?: PaymentMethod;
    /**
     * The document\'s gross total price.
     * @type {number}
     * @memberof Document
     */
    'gross_total'?: number;
    /**
     * 
     * @type {Currency}
     * @memberof Document
     */
    'currency'?: Currency;
    /**
     * 
     * @type {number}
     * @memberof Document
     */
    'conversion_rate'?: number;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'invoice_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'fulfillment_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'due_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'paid_date'?: string;
    /**
     * 
     * @type {DocumentOrganization}
     * @memberof Document
     */
    'organization'?: DocumentOrganization;
    /**
     * 
     * @type {Partner}
     * @memberof Document
     */
    'partner'?: Partner;
    /**
     * 
     * @type {DocumentPartner}
     * @memberof Document
     */
    'document_partner'?: DocumentPartner;
    /**
     * 
     * @type {boolean}
     * @memberof Document
     */
    'electronic'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Document
     */
    'comment'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Document
     */
    'tags'?: Array<string>;
    /**
     * 
     * @type {DocumentNotificationStatus}
     * @memberof Document
     */
    'notification_status'?: DocumentNotificationStatus;
    /**
     * 
     * @type {DocumentLanguage}
     * @memberof Document
     */
    'language'?: DocumentLanguage;
    /**
     * 
     * @type {Array<DocumentItem>}
     * @memberof Document
     */
    'items'?: Array<DocumentItem>;
    /**
     * 
     * @type {DocumentSummary}
     * @memberof Document
     */
    'summary'?: DocumentSummary;
    /**
     * 
     * @type {DocumentSettings}
     * @memberof Document
     */
    'settings'?: DocumentSettings;
    /**
     * 
     * @type {OnlineSzamlaStatusEnum}
     * @memberof Document
     */
    'online_szamla_status'?: OnlineSzamlaStatusEnum;
    /**
     * 
     * @type {Array<DocumentAncestor>}
     * @memberof Document
     */
    'related_documents'?: Array<DocumentAncestor>;
    /**
     * 
     * @type {Discount}
     * @memberof Document
     */
    'discount'?: Discount;
    /**
     * 
     * @type {CorrectionType}
     * @memberof Document
     */
    'correction_type'?: CorrectionType;
}



