/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentFormat } from './document-format';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentType } from './document-type';

/**
 * 
 * @export
 * @interface InvoiceSettings
 */
export interface InvoiceSettings {
    /**
     * 
     * @type {DocumentType}
     * @memberof InvoiceSettings
     */
    'document_type'?: DocumentType;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSettings
     */
    'fulfillment_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSettings
     */
    'due_date'?: string;
    /**
     * 
     * @type {DocumentFormat}
     * @memberof InvoiceSettings
     */
    'document_format'?: DocumentFormat;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSettings
     */
    'comment'?: string;
}



