/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import { Discount } from './discount';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentForm } from './document-form';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentLanguage } from './document-language';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentMethod } from './payment-method';

/**
 * 
 * @export
 * @interface PartnerCustomBillingSettings
 */
export interface PartnerCustomBillingSettings {
    /**
     * 
     * @type {PaymentMethod}
     * @memberof PartnerCustomBillingSettings
     */
    'payment_method'?: PaymentMethod;
    /**
     * 
     * @type {DocumentForm}
     * @memberof PartnerCustomBillingSettings
     */
    'document_form'?: DocumentForm;
    /**
     * 
     * @type {number}
     * @memberof PartnerCustomBillingSettings
     */
    'due_days'?: number;
    /**
     * 
     * @type {Currency}
     * @memberof PartnerCustomBillingSettings
     */
    'document_currency'?: Currency;
    /**
     * 
     * @type {DocumentLanguage}
     * @memberof PartnerCustomBillingSettings
     */
    'template_language_code'?: DocumentLanguage;
    /**
     * 
     * @type {Discount}
     * @memberof PartnerCustomBillingSettings
     */
    'discount'?: Discount;
}



