/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const PaymentMethod = {
    Aruhitel: 'aruhitel',
    Bankcard: 'bankcard',
    Barion: 'barion',
    Barter: 'barter',
    Cash: 'cash',
    CashOnDelivery: 'cash_on_delivery',
    Coupon: 'coupon',
    EloreUtalas: 'elore_utalas',
    EpKartya: 'ep_kartya',
    Kompenzacio: 'kompenzacio',
    Levonas: 'levonas',
    OnlineBankcard: 'online_bankcard',
    Other: 'other',
    Paylike: 'paylike',
    Payoneer: 'payoneer',
    Paypal: 'paypal',
    PaypalUtolag: 'paypal_utolag',
    Payu: 'payu',
    PickPackPont: 'pick_pack_pont',
    PostaiCsekk: 'postai_csekk',
    Postautalvany: 'postautalvany',
    Skrill: 'skrill',
    SzepCard: 'szep_card',
    Transferwise: 'transferwise',
    Upwork: 'upwork',
    Utalvany: 'utalvany',
    Valto: 'valto',
    WireTransfer: 'wire_transfer'
} as const;

export type PaymentMethod = typeof PaymentMethod[keyof typeof PaymentMethod];



