/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import { Entitlement } from './entitlement';
// May contain unused imports in some cases
// @ts-ignore
import { Vat } from './vat';

/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    'name': string;
    /**
     * 
     * @type {Currency}
     * @memberof Product
     */
    'currency': Currency;
    /**
     * 
     * @type {Vat}
     * @memberof Product
     */
    'vat': Vat;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    'unit': string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    'comment'?: string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    'net_unit_price'?: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    'general_ledger_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    'general_ledger_taxcode'?: string;
    /**
     * 
     * @type {Entitlement}
     * @memberof Product
     */
    'entitlement'?: Entitlement;
}



