/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentType } from './document-type';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentMethod } from './payment-method';
// May contain unused imports in some cases
// @ts-ignore
import { ReceiptInsertItemsInner } from './receipt-insert-items-inner';

/**
 * 
 * @export
 * @interface ReceiptInsert
 */
export interface ReceiptInsert {
    /**
     * 
     * @type {number}
     * @memberof ReceiptInsert
     */
    'block_id': number;
    /**
     * 
     * @type {DocumentType}
     * @memberof ReceiptInsert
     */
    'type': DocumentType;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof ReceiptInsert
     */
    'payment_method': PaymentMethod;
    /**
     * 
     * @type {Currency}
     * @memberof ReceiptInsert
     */
    'currency': Currency;
    /**
     * 
     * @type {string}
     * @memberof ReceiptInsert
     */
    'vendor_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReceiptInsert
     */
    'partner_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReceiptInsert
     */
    'name'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReceiptInsert
     */
    'emails'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ReceiptInsert
     */
    'conversion_rate'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReceiptInsert
     */
    'electronic'?: boolean;
    /**
     * 
     * @type {Array<ReceiptInsertItemsInner>}
     * @memberof ReceiptInsert
     */
    'items'?: Array<ReceiptInsertItemsInner>;
}



