/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SpendingListItem } from './spending-list-item';

/**
 * An object with a data property that contains an array of up to limit spending. Each entry in the array is a separate spending object. If no more spending are available, the resulting array will be empty.
 * @export
 * @interface SpendingList
 */
export interface SpendingList {
    /**
     * 
     * @type {Array<SpendingListItem>}
     * @memberof SpendingList
     */
    'data'?: Array<SpendingListItem>;
    /**
     * 
     * @type {number}
     * @memberof SpendingList
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingList
     */
    'per_page'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingList
     */
    'current_page'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingList
     */
    'last_page'?: number;
    /**
     * 
     * @type {string}
     * @memberof SpendingList
     */
    'prev_page_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpendingList
     */
    'next_page_url'?: string;
}

