/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Category } from './category';
// May contain unused imports in some cases
// @ts-ignore
import { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import { SpendingPartner } from './spending-partner';
// May contain unused imports in some cases
// @ts-ignore
import { SpendingPaymentMethod } from './spending-payment-method';

/**
 * 
 * @export
 * @interface SpendingListItem
 */
export interface SpendingListItem {
    /**
     * 
     * @type {number}
     * @memberof SpendingListItem
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingListItem
     */
    'organization_id'?: number;
    /**
     * 
     * @type {Category}
     * @memberof SpendingListItem
     */
    'category'?: Category;
    /**
     * 
     * @type {string}
     * @memberof SpendingListItem
     */
    'paid_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SpendingListItem
     */
    'fulfillment_date'?: string;
    /**
     * 
     * @type {SpendingPartner}
     * @memberof SpendingListItem
     */
    'partner'?: SpendingPartner;
    /**
     * 
     * @type {string}
     * @memberof SpendingListItem
     */
    'invoice_number'?: string;
    /**
     * 
     * @type {Currency}
     * @memberof SpendingListItem
     */
    'currency'?: Currency;
    /**
     * 
     * @type {number}
     * @memberof SpendingListItem
     */
    'conversion_rate'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingListItem
     */
    'total_gross'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingListItem
     */
    'total_gross_local'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingListItem
     */
    'total_vat_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof SpendingListItem
     */
    'total_vat_amount_local'?: number;
    /**
     * 
     * @type {string}
     * @memberof SpendingListItem
     */
    'invoice_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpendingListItem
     */
    'due_date'?: string;
    /**
     * 
     * @type {SpendingPaymentMethod}
     * @memberof SpendingListItem
     */
    'payment_method'?: SpendingPaymentMethod;
    /**
     * 
     * @type {string}
     * @memberof SpendingListItem
     */
    'comment'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SpendingListItem
     */
    'is_created_by_nav'?: boolean;
}



