/* tslint:disable */
/* eslint-disable */
/**
 * Billingo API v3
 * This is a Billingo API v3 documentation. Our API based on REST software architectural style. API has resource-oriented URLs, accepts JSON-encoded request bodies and returns JSON-encoded responses. To use this API you have to generate a new API key on our [site](https://app.billingo.hu/api-key). After that, you can test your API key on this page.
 *
 * The version of the OpenAPI document: 3.0.14
 * Contact: hello@billingo.hu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const Vat = {
    _0: '0%',
    _1: '1%',
    _10: '10%',
    _11: '11%',
    _12: '12%',
    _13: '13%',
    _14: '14%',
    _15: '15%',
    _16: '16%',
    _17: '17%',
    _18: '18%',
    _19: '19%',
    _2: '2%',
    _20: '20%',
    _21: '21%',
    _22: '22%',
    _23: '23%',
    _24: '24%',
    _25: '25%',
    _26: '26%',
    _27: '27%',
    _3: '3%',
    _4: '4%',
    _5: '5%',
    _55: '5,5%',
    _6: '6%',
    _7: '7%',
    _77: '7,7%',
    _8: '8%',
    _9: '9%',
    _95: '9,5%',
    Aam: 'AAM',
    Am: 'AM',
    Eu: 'EU',
    Euk: 'EUK',
    FAfa: 'F.AFA',
    Fad: 'FAD',
    KAfa: 'K.AFA',
    Maa: 'MAA',
    Tam: 'TAM',
    Kk: 'ÁKK',
    Thk: 'ÁTHK'
} as const;

export type Vat = typeof Vat[keyof typeof Vat];



